"""Add tenant_applications and property agreement fields

Revision ID: 15823d28be23
Revises: 6a4bfa14d613
Create Date: 2026-02-27 01:18:47.780148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15823d28be23'
down_revision = '6a4bfa14d613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_agreement_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('tenant_agreement_url')

    # ### end Alembic commands ###
