"""add settings and property interactions

Revision ID: 6a4bfa14d613
Revises: 88c995e1b7a1
Create Date: 2026-02-27 00:38:10.972224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4bfa14d613'
down_revision = '88c995e1b7a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_clicks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('call_clicks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('map_clicks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('map_clicks')
        batch_op.drop_column('call_clicks')
        batch_op.drop_column('whatsapp_clicks')
        batch_op.drop_column('like_count')

    # ### end Alembic commands ###
