"""add multi unit support

Revision ID: 7e4ba49d35d5
Revises: 
Create Date: 2026-02-26 15:14:54.982648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e4ba49d35d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_agreement_fee', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('units', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('location_description', sa.Text(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('bedrooms',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('bathrooms',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('area',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('area',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('bathrooms',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('bedrooms',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.drop_column('location_description')
        batch_op.drop_column('units')
        batch_op.drop_column('tenant_agreement_fee')

    # ### end Alembic commands ###
